### ISSUE TITLE
Mercurial dependencies in paket.dependencies - space in branch name

### ISSUE THREAD

**Issue by klesta490** [tomasdeml/Paket#1]
### paket.dependencies file does not support space in branch name

I want to reference mercurial branch **my feature** in paket.dependencies file. 
Paket ends with error. 

### Repro steps

1) In repository referenced by packet create branch, that has space in name.
2) Try use this branch by changing paket.dependencies file
3) Run paket update

### Expected behavior

Branch is switched.

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/921463/21682096/ee2c5d56-d352-11e6-909e-cb107edef61d.png)

### Known workarounds
Do not use space in branch name

**Comment by tomasdeml** [comment]
Thanks for the report, the issue is fixed in latest version. Give it a try! 🚀
